portal/static/index.html
portal/static/walrus-sites-portal-register-sw.js

feat(portal): show "browser not supported" message

---

.github/ISSUE_TEMPLATE/code-bug.yaml
.github/ISSUE_TEMPLATE/feature-request.yaml

- add bug report issue template
- add feature request issue template

chore(docs): create issue template for features and bugs

---

portal/common/lib/page_fetching.ts

fix(portal): ensure that 404 is fetched when we can't find a resource

---

portal/common/lib/page_fetching.ts

This simplifies the code of the `resolveAndFetchPage()`.

refactor(portal): resolve the objectId to a separate function

---

portal/common/lib/http/http_error_responses.ts

Closes partially https://github.com/MystenLabs/walrus-sites/issues/195 - Random Suifrens will be added in a different PR

feat(landing-page): Change the message of the Response404

---

portal/worker/src/walrus-sites-sw.ts

fix(portal): remove duplicate requests from sw

---

site-builder/src/main.rs

minor refactor.
- uses the already existing default selection function
- simplifies the selection of paths.

refactor: check default directories

---

site-builder/src/publish.rs
site-builder/src/site/resource.rs

Adds a `--max-concurrent <LIMIT>` cli flag to the `publish` and `update` commands. If specified, it limits the number of concurrent calls to the Walrus CLI to compute the blob ID.
This is useful to reduce the memory footprint of the site builder, at the cost of a longer time spent computing blob IDs.

feat(site-builder): add option to limit parallel blob ID computation

---

.github/workflows/tag.yml

ci: Create new tagging workflow

---

portal/common/lib/logger.ts
portal/common/lib/page_fetching.ts
portal/server/app/route.ts

- Create a new debug level, used as the highest level of logging.
- Add more descriptive comments to the logger class.
- Update the logging level of some of the logs used in the server portal.

feat(common): add a new -debug- logging level

---

portal/pnpm-lock.yaml
portal/server/app/layout.tsx
portal/server/package.json

This will automatically start tracking
visitors and page views with Web Analytics
Changes:
- Create a root `layout.tsx`.
- Add to it the Analytics component.

feat(portal): integrate vercel web analytics

---

portal/common/lib/aggregator.ts
portal/common/lib/redirects.test.ts
site-builder/src/main.rs
site-builder/src/publish.rs
site-builder/src/site/manager.rs
site-builder/src/walrus.rs
site-builder/src/walrus/command.rs

chore: updates for walrus redeployment

---

site-builder/src/walrus.rs
site-builder/src/walrus/command.rs
site-builder/src/walrus/output.rs

fix: align with changed Walrus `info` command

---

portal/bun.lock
portal/server/app/route.ts
portal/server/package.json
portal/server/src/amplitude.ts
portal/server/src/configuration_loader.ts
portal/server/src/utils.ts
portal/server/src/web_analytics.ts

Integrate amplitude event tracking with the aim to gradually migrate from vercel web analytics.
Currently the use of Amplitude doesn't disable web analytics in order for us to make a smooth transition.

feat: sew 26 amplitude integration along with web analytics

---

portal/blocklist_api/src/redis.ts

we should never issue a `connect()` multiple times

fix: we should never issue a `connect()` multiple times

---

portal/common/lib/decompress_data.test.ts
portal/common/lib/decompress_data.ts

Note: currently we don't use anywhere this function. But we might need to decompress zipped files on the portal side at some point.

feat(common): decompress chunk by chunk

---

portal/bun.lock

Without this the docker builds will fail.

fix: bump bun.lock to align with grafana changes

---

portal/common/lib/suins.test.ts
portal/common/lib/suins.ts

Only resolve when "link to walrus site" is used ignoring when the linked to wallet is used.

feat(suins): only resolve when "link to walrus site" is used 

---

move/walrus_site/README.md

Create a README file so that it is displayed in the MVR: https://www.moveregistry.com/package/@walrus/sites

docs(contract): create README for MVR

---

.github/actions/deploy/action.yml
.github/workflows/build.yml
.github/workflows/code.yml
.github/workflows/deploy-snake.yml
.github/workflows/deploy-vite-react-ts.yml
.github/workflows/lint.yml
.github/workflows/move-tests.yml
.github/workflows/portal-tests.yml
.github/workflows/tag.yml

Pins github actions to commit SHAs

chore: Update and pin actions to specific SHA

---

.github/workflows/code.yml
Cargo.lock
rust-toolchain.toml
site-builder/Cargo.toml
site-builder/src/args.rs
site-builder/src/lib.rs
site-builder/src/publish.rs
site-builder/src/site.rs
site-builder/src/site/builder.rs
site-builder/src/site/contracts.rs
site-builder/src/site/manager.rs
site-builder/src/site/resource.rs
site-builder/src/types.rs
site-builder/src/util.rs
site-builder/src/walrus.rs
site-builder/src/walrus/command.rs
site-builder/src/walrus/output.rs
site-builder/src/walrus/types.rs
site-builder/tests/localnode/args_builder.rs
site-builder/tests/localnode/mod.rs
site-builder/tests/publish.rs
site-builder/tests/publish_quilts.rs
sonar-project.properties

Introduces walrus cli interface to do quilt-operations
Publishes site via `publish-quilts` with feature-flag "quilts-experimental"

feat(site-builder): Sew 247 site builder publish using quilts

---

.github/actions/deploy/action.yml

Support bech32 suiprivkey and secret-phrase private keys as exported from Slush wallet.

ci: Deploy action, support wallet exported keys

---

Cargo.lock
Cargo.toml
deny.toml
portal/bun.lock
portal/server/custom_logger.ts
portal/server/package.json
portal/worker/package.json
site-builder/Cargo.toml
site-builder/src/publish.rs
site-builder/src/site/builder.rs
site-builder/src/site/manager.rs
site-builder/src/site/resource.rs
site-builder/src/unit_tests/site.builder.tests.rs
site-builder/src/unit_tests/util.tests.rs
site-builder/src/util.rs
site-builder/tests/convert.rs
site-builder/tests/localnode/mod.rs
site-builder/tests/publish_quilts.rs
site-builder/tests/quilts_dry_run_regression.rs
site-builder/tests/update_quilts.rs

Rebase to main for the latest v1.2.1 changes.

chore(release): Update testnet to v1.2.1
