MystenLabs/walrus-sites

portal/src/sw.ts
Works great overall. Very smooth.
One improvement I'd like: custom 404 blob for a site, something that would be returned for the site if there's nothing found for the path.
Take a look at the sample site I deployed: https://1e1maorotlxkr4feuf7m9jqliu9j12dlr8lxvt28u23f3lur5s.walrus.site/
Everything just works, out of the box, awesome, I was like going to cancel my Heroku plan.
The only thing is that if you navigate to links from the page with history api:
https://1e1maorotlxkr4feuf7m9jqliu9j12dlr8lxvt28u23f3lur5s.walrus.site/ -> https://1e1maorotlxkr4feuf7m9jqliu9j12dlr8lxvt28u23f3lur5s.walrus.site/capsule/0xfd72e8611ed8ebfa2f93acf9640bd8a5096923880feeeae7fabc96d4f6cffab2
it shows the page, but shows 404 if you do refresh. Which is expected, and we can use hash-navigation as a workaround, …
=> feat(portal): fallback to 404.html blob if available

portal/static/sw.js
Fixes the problem some clients experienced after having renamed the service worker file (#98 ).
The re-introduced `/sw.js` should be removed after sufficient time has passed (#101 ).
=> fix(portal): force old sw uninstall

site-builder/src/main.rs, site-builder/src/preprocessor.rs, site-builder/src/publish.rs, site-builder/src/site/resource.rs
Mimics Python's `list_directory` function when calling `http.server` on a directory without `index.html`.
Closes #84
=> feat(site-builder): add preproc to publish directories with files

site-builder/src/main.rs, site-builder/src/publish.rs
Deduplicate the arguments of Publish and Update
commands. 
There was a duplication of some fields that were
shared among the publish and update.
The overlapping options were consolidated by
creating a PublishOptions struct that is then
added to both commands.
This new struct is also used in the publish_site
and update_site functions resolving the
"too many arguments" issue.
- Rebuild the `site-builder` executable: 
```shell  
cargo build --release 
```
- Publish the example site: 
```shell
./target/release/site-builder --config site-builder/assets/builder-example.yaml publish ./examples/snake
``` 
- Update the site using the object id from the above: 
```shell
./target/release/site-builder --config site-builder/assets/builder-example.yaml update ./examples/snake 0x4f5...
```
=> refactor(site-builder): deduplicate args for publish and update

site-builder/src/site/resource.rs
So far the `site-builder` was silently ignoring empty files.
This PR adds a check that raises an error when an empty file is included in the directory that is to be published.
Also, the check should be done before trying to create a walrus blob id.   
i.e. 
```shell
❯ ./target/release/site-builder --config site-builder/assets/builder-example.yaml publish examples/snake/
...
Parsing the directory examples/snake/ and locally computing blob IDs ...
Error during execution
Error: error while reading resource `examples/snake/empty.txt`
Caused by:
0: Walrus sites does not support empty files.
1: The file examples/snake/empty.txt is empty.
```
=> feat(site-builder): on publish raise an error when a file is empty

site-builder/src/site/resource.rs
Treat files without or with unknown
extension as binary files.
Whenever the dir that is to be published contains a file with no extension 
(e.g. `file`) or an unknown extension (e.g. `file.<unknown>`), a binary
content type will be assigned to it, and a warning will be shown.
The octet-stream content type indicates
a response body with arbitrary binary data
as defined in RFC 2046.
https://datatracker.ietf.org/doc/html/rfc2046#section-4.5.1
Given the following tree structure:
```
snake
├── Oi-Regular.ttf
├── file.UNKNOWN_EXTENSION  <----- [!]
├── index.html
└── walrus.svg
```  
And running `./target/release/site-builder --config site-builder/assets/builder-example.yaml publish examples/snake/`
Returns: 
```
[...]
Parsing the directory examples/snake/ and locally computing blob IDs ... …
```
=> feat(site-builder): treat unknown file extensions defaulting to arbitrary binary data

portal/src/http_status_codes.ts, portal/src/walrus-sites-sw.ts
When recursively redirecting to the object ids of a Display, keep track of the "visited" object ids to avoid 
infinite loops. Source: https://github.com/MystenLabs/walrus-sites/pull/58#discussion_r1635253806
Also refactored the return type of the fetchResource function It would return `null` for cases where the resource would not be able to load. 
This is not ideal, since we need to be more expressive with our responses (we introduce another error of INFINITE_LOOPS 508 and 310 for maximum number of redirects reached). 
Using an http status codes enum enables us to propagate the nature of those errors to the response of `fetchPage`.
=> feat(service-worker): track seen resources to avoid infinite redirect loops

.github/workflows/portal-tests.yml, portal/package.json, portal/pnpm-lock.yaml, portal/src/helpers/domain_parsing.test.ts, portal/src/helpers/domain_parsing.ts, portal/src/types/index.ts, portal/src/walrus-sites-sw.ts, portal/tsconfig.json, portal/unit_tests/domain_parsing.test.ts, portal/webpack.config.common.js
We are currently supporting only a pattern of domains like this `0x123.walrus.sites`.
This PR makes it possible to:
- Parse more complex domains: `0x123.localhost:8080`, `0x123.walrus.co.uk`
- Support suins subnames: `subsubname.subname.suinsname.walrus.sites`
- Includes some unit tests so that we can have more confidence on the function's results. Gradually we can extend our code coverage. 
Connected issues:
- Closes https://github.com/MystenLabs/walrus-sites/issues/32
- Closes https://github.com/MystenLabs/walrus-sites/issues/26
=> feat(portal): Add support for tlds and suins subnames

portal/common/lib/domain_parsing.ts, portal/server/app/route.ts, portal/server/vercel.json
Resolves https://github.com/MystenLabs/walrus-sites/issues/147
Add the functionality so that while browsing the landing page of the server portal fetch the page contents by the worker portal.
This is a temporary solution in order to make the server side portal work. 
As an improvement to this, in a following PR we can consider redirecting to fetch the page from another service on vercel (similar to how the worker portal works).
=> fix(portal): fix landing page server portal infinite loop

portal/server/vercel.json
Server portal deployment was failing on vercel due to a cryptic `EDGE_FUNCTION_INVOCATION_FAILED` error.
To fix it I had to specify `"framework": "nextjs"` on `vercel.json`.
=> fix(portal): edge function invocation failed

portal/server/app/route.ts
While fetching `walrus.site/index.html` is registering a service worker, which
we don't want in our server portal implementation.
`index-sw-enabled.html` in the same, but without the service worker registration.
=> fix(portal): fetch walrus sites index sw enabled

site-builder/src/site/resource.rs
This should only be merged after the re-deployment of the Walrus Devnet.
Closes #125
=> feat(site-builder): allow empty files

portal/server/app/route.ts, publish_landing_page.sh
While publishing the landing page to walrus,
the `index-sw-enabled.html` is renamed to `index.html` to avoid resolving this mapping on
`portal/server/app/route.ts`.
=> refactor(portal): Rename index-sw-enabled.html upon publish landing page

.github/ISSUE_TEMPLATE/code-bug.yaml, .github/ISSUE_TEMPLATE/feature-request.yaml
Removes the `[title]:` titles for consistency
=> chore: change issue templates to match walrus-docs

portal/common/lib/constants.ts, portal/common/static/walrus-sites-portal-register-sw.js, portal/worker/src/walrus-sites-portal-register-sw.ts, portal/worker/tsconfig.json, portal/worker/webpack.config.common.js
Some browsers (like in-app browsers) don't support service workers.
Instead of throwing an error to the user, we
redirect to `blob.store`, where the resolution of the site resources happens on the server side.
=> feat(service-worker): Redirect to blob.store if SW not able to install

portal/common/lib/page_fetching.ts, portal/common/lib/resource.ts, portal/common/lib/types/index.ts, portal/worker/src/caching.ts, portal/worker/src/walrus-sites-sw.ts
Create a caching mechanism on the service worker. 
Caches are expired when:
1. The timestamp is too old
2. The cached sui object version of the `site::Resource` does not match the one that is on-chain. 
~~The `caches` api is only available for "secure contexts" so in order to test this locally one needs to use a tool like `mkcert` for local https certs.~~ 
Localhost is a secure context, so no need to issue a cert to test this. If you still experience issues with the browser's state, use chrome's incognito mode.
=> feat(portal): add caching to the service worker

.github/workflows/codspeed.yml, portal/common/lib/decompress_data.bench.ts, portal/common/lib/http/http_error_responses.ts, portal/common/lib/page_fetching.bench.ts, portal/common/lib/page_fetching.ts, portal/common/lib/resource.bench.ts, portal/common/lib/resource.test.ts, portal/common/lib/types/index.ts, portal/common/package.json, portal/common/tsconfig.json, portal/common/vite.config.mts, portal/common/vite.config.ts, portal/pnpm-lock.yaml
In this PR we create [vitest benchmarks](https://vitest.dev/api/#bench) plus a codspeed integration for easier monitoring.
> bench defines a benchmark. In Vitest terms benchmark is a function that defines a series of operations. Vitest runs this function multiple times to display different performance results.
By specifying a `<module_name>.bench.ts`, you can run `vitest bench` and get results like so:
```shell
✓ lib/page_fetching.bench.ts (1) 3089ms
name                                    hz     min     max    mean     p75     p99    p995    p999      rme  samples
· fetch the landing page walrus site  6.5386  132.51  288.17  152.94  141.06  288.17  288.17  288.17  ±22.45%       10
BENCH  Summary
```
TODO 
Access the dashboard at: https://codspeed.io/MystenLabs/walrus-sites
Right now …
=> feat(portal): integrate vitest benchmarks

portal/common/lib/resource.test.ts, portal/common/lib/resource.ts
Inside `fetchResource` when a redirectId is found,
there was a `client.getObject` call to fetch the
`redirectPage.data` and check if the page data exist.
This is redundant, as this is already checked
when fetching the `pageData` a few lines bellow,
so we can emit the aforementioned check, and
directly recur calling `fetchResource`.
Bonus: 
- remove redundant `else` clause
- update fetchResource tests in order to pass (it's no longer
needed to mock all those getObject calls, which is also an indicator
of the performance improvement here).
=> refactor: Remove redundant pageData fetch

.github/workflows/codspeed.yml
The fact that the branch that codspeed monitors was set to **master**, resulted in the performance graphs not showing to the dashboard: https://codspeed.io/MystenLabs/walrus-sites/benchmarks
With that quick fix this should be fine now.
=> fix(codspeed): use main instead of master

portal/common/static/404-page.template.html
Closes #190 
Page 404 would provide a link for
walrus.site, even when the server side
portal is used (blob.store).
Created a new function that extracts the 
appropriate redirection
link based on the current URL in order to
point to the correct portal, and uses it
to the `<a href=...>` tag.
i.e. if the user typed `<name>.walrus.site`
he should be redirected to `walrus.site` when
clicking the hyperlink.
Likewise, if the user typed `<name>.blob.store`, 
he should be redirected to `blob.store`.
=> fix(portal): extract portal link

portal/common/lib/constants.ts, portal/common/lib/page_fetching.bench.ts, portal/common/lib/resource.bench.ts
Bench flatland with fetchPage and fetchResource.
The addition was simple: use the already existing bench files for fetchPage and fetchResource, 
create some abstractions to keep it DRY, and include the flatland WS objectId.
=> feat(portal): Bench flatland - fetchPage & fetchResource

portal/common/lib/resource.test.ts, portal/common/lib/resource.ts
Performance improvement! 🏁
`Promise.all` is as slow as it is the slowest of
the Promises it contains.
So far we have been combining `checkRedirect` and `dynamicFieldObject` fetching
in the same `Promise.all` clause. But `checkRedirect` is quite slow, and it's a case
that is not that frequent (currently only flatland makes use of it).
Given the above, we could start by fetching the dynamicFieldObject first. 
If an object has `dynamicFields` of `RESOURCE_PATH_MOVE_TYPE` it means it's a resource,
which also means that **there won't be any redirect**.
On the other hand, if the "dynamicField fetching" flow fails, then an error will be thrown in order to be caught by the `checkRedirect` and check if it's really a "redirect-able" object.
**Bonus changes**
+ refactored the fetchResource a bit
+ …
=> feat(portal): Improve fetchResource performance

Cargo.lock, site-builder/Cargo.toml, site-builder/src/main.rs
**Goal**
Have the following to work same as the way the sui binary works:
```
site-builder --version 
site-builder -V
```
**Why?**
Help Suibase scripts to maintain latest binary versions for its devs.
**Implementation**
Trivial cut&paste of how sui binary already handles this (using Mysten Labs bin-version crate).
**Tests**
=> feat(site-builder): Add --version support

portal/common/lib/bcs_data_parsing.ts, portal/common/lib/constants.ts, portal/common/lib/page_fetching.ts, portal/common/lib/types/index.ts
Updates the portal to align with the changes in #210.
In detail, parse the resource headers, replacing the hard-coded content-type and content-encoding with the ones parsed from the contract. 
Also, redeploy the landing page and flatland, to align with the new walrus sites contract.
=> feat(portal): parse HTTP headers from resource

Cargo.lock, deny.toml, move/walrus_site/sources/site.move, portal/common/lib/bcs_data_parsing.ts, portal/common/lib/page_fetching.ts, site-builder/Cargo.toml, site-builder/src/main.rs, site-builder/src/publish.rs, site-builder/src/site/builder.rs, site-builder/src/site/config.rs, site-builder/src/site/content.rs, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs, site-builder/src/util.rs
A list of many small changes:
* Cleans up some unused structs, removes unused dependencies.
* Bumps the sui versions, prevents cargo deny from complaining.
* Uniforms comments.
* Fetches the correct configuration file from the root site directory, and does not upload it with the site.
* **Does not reupload unchanged resources** - there was a bug in the comparison of the headers.
=> chore(site-builder): small improvements and fixes

portal/worker/src/caching.ts
In case the cache storage of the service worker if full, a QuotaExceededError will be raised. 
To handle it, I delete the oldest 50 entries in the SW storage.
=> feat(service-worker): handle cache storage overflow

site-builder/src/site/builder.rs, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs, site-builder/src/summary.rs
In this PR, we address the issue of potential missing blobs on Walrus due to devnet wipes. We ensure that resources in the Sui object that appear unchanged are re-uploaded to Walrus if necessary, preventing discrepancies between on-chain data and Walrus storage.
**Changes:**
Unchanged Resource Operation:
-  Added ResourceOp::Unchanged to handle resources that appear unchanged but may still need re-uploading.
-  Calculate unchanged resources inside diff function.
-  Modified publish_to_walrus to process both Created and Unchanged resources.
=> feat(site-builder): new unchanged resource operation

Cargo.lock, site-builder/Cargo.toml, site-builder/assets/builder-example.yaml, site-builder/src/publish.rs, site-builder/src/site.rs, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs, site-builder/src/summary.rs, site-builder/src/walrus.rs, site-builder/src/walrus/command.rs, site-builder/src/walrus/output.rs
Makes calling the site builder on large sites (tens/hundreds of files) much faster, especially in the case of small site updates. 
* parallelizes calls to the walrus CLI that can be made safely without locking objects.
* reduces the number of calls to the fullnodes by keeping the number of shards.
* only performs update checks when the command is a `--force`.
Example of improvement: a site with 50 files of 1KB each (`before -> after`):
- publish operation: `157s -> 102s`
- update with no changes: `67s -> 5s`
- update with 1-file change `70s -> 15s`
=> feat(site-builder): parallelize calls to the walrus cli

.github/workflows/codspeed.yml, .github/workflows/lint.yml, portal/common/lib/constants.ts, portal/server/app/route.ts, portal/server/next-env.d.ts, portal/worker/src/walrus-sites-sw.ts
Makes possible requests that are made on testnet, to be forwarded and retried on a portal that supports devnet. 
This way we can support old deployments that still have not migrated to testnet.
The [fallback devnet portal](https://vercel.com/mysten-labs/walrus-sites-sp-devnet-fallback) is a server side portal running the code of commit 3e693ad09d2670472e9d921b1dfab17166b6a9f6 (deployed using the branch [temp/devnet](https://github.com/MystenLabs/walrus-sites/tree/temp/devnet)). 
This is the state of our old walrus sites version (before reaching v.1.0.0), i.e. supporting only the devnet deployments, anything prior to the current date (2024/10/11).
=> feat(portal): propagate requests to a fallback devnet portal

portal/common/lib/bcs_data_parsing.ts, portal/common/lib/objectId_operations.test.ts, portal/common/lib/objectId_operations.ts, portal/common/lib/page_fetching.bench.ts, portal/common/lib/page_fetching.ts, portal/common/lib/resource.bench.ts, portal/common/lib/resource.test.ts, portal/common/lib/resource.ts, portal/common/lib/routing.ts, portal/common/package.json, portal/pnpm-lock.yaml
- Upgrade @mysten/sui to 1.12.0
This version includes the `deriveDynamicFieldID`
function needed to calculate the DF object ID
without making a request to a fullnode.
- Replace `client.getDynamicFieldObject` with `deriveDynamicFieldID`.
- Skip `page_fetching` benchmarks. The results we get from it are misleading and slow down development whenever there are changes happening in its' dependencies. In the near future we should revisit how to properly bench this. https://github.com/MystenLabs/walrus-sites/issues/250
TODO (following PR)
- ⚡ Performance improvement: Use `multiGetObjects` to fetch both the display and the dynamic field object in the same request.
=> feat(common-lib): derive dynamic field instead of call to fullnode 

portal/common/lib/page_fetching.ts, portal/common/lib/resource.test.ts, portal/common/package.json, portal/pnpm-lock.yaml, portal/server/app/route.ts, portal/server/package.json, portal/worker/package.json, portal/worker/src/caching.ts, portal/worker/src/walrus-sites-sw.ts
The cache was not checking that the suins name for a site had not been changed. 
Therefore, if it was changed, the cache would not refresh.
The changes are a bit ugly and painful. I think it's soon going to be time to sit down and and improve the architecture of the worker and library.
=> fix: add check that suins name has not changed to cache

portal/server/app/route.ts, portal/worker/src/walrus-sites-sw.ts, portal/worker/webpack.config.prod.js
Additionally, show when the fallback is used also in prod.
Useful for checking if a site has been updated or not.
=> fix: ensure the fallback returns uncompressed responses 

.github/workflows/code.yml, Cargo.lock, examples/snake/ws-resources.json, site-builder/Cargo.toml, site-builder/src/site/resource.rs
Checks the paths defined in `ws-resources.yaml` and if the resource path matches the pattern defined in the yaml, it adds the corresponding http headers to the `Resource::headers` vecmap.
=> feat: support wildcards in http headers

portal/server/app/route.ts, portal/worker/src/walrus-sites-sw.ts
The portal previously included a mechanism to redirect requests to devnet as a fallback in the event of a failure or a 404 (Not Found) response. **This pull request removes that fallback functionality**.
**Changes** 
- Removed the fallback to FALLBACK_DEVNET_PORTAL in the main routing logic.
- Simplified the fetch process by eliminating proxyFetch and fallback handling.
- Streamlined code to directly return responses or appropriate errors without devnet fallback references.
=> feat(portal): remove devnet fallback

site-builder/src/site/manager.rs, site-builder/src/util.rs
The site builder now uses multiple ptbs in case the site update requires more than 200 resource operations.
=> feat(site-builder): use multiple ptbs to upload large sites

portal/common/lib/domain_parsing.test.ts, portal/common/lib/domain_parsing.ts, portal/common/lib/redirects.ts, portal/server/app/route.ts, portal/server/next-env.d.ts, portal/worker/src/walrus-sites-sw.ts
- Add a new `portalNameLength` wherever it applies. 
- Update the `domain_parsing.tests` to cover the new functionality.
The PR is pointing to the `testnet` branch as it is the best branch to test this. 
It uses a `sw-tnet.blocksite.net` domain + the environment variables of the portal name length have already been set. 
Note: In the future, if we make the common library more object oriented, this awkward argument passing can be avoided.
=> feat(portal): update portal domain name resolution using length

portal/common/lib/domain_parsing.test.ts, portal/common/lib/domain_parsing.ts, portal/common/lib/redirects.ts, portal/server/app/route.ts, portal/server/next-env.d.ts, portal/worker/src/walrus-sites-sw.ts, portal/worker/webpack.config.common.js
The service worker is not working on the testnet service worker portal because it can't access the process object. 
I had to specify the PORTAL_DOMAIN_NAME_LENGTH in the webpack config, so that it is defined upon the build phase.
=> fix(service-worker): sw PORTAL_DOMAIN_NAME_LENGTH unavailable

portal/common/lib/constants.ts, portal/common/lib/node_selector.ts, portal/common/lib/page_fetching.ts, portal/common/lib/resource.test.ts, portal/common/lib/resource.ts, portal/common/lib/routing.test.ts, portal/common/lib/routing.ts, portal/common/lib/rpc_selector.ts, portal/common/lib/suins.test.ts, portal/common/lib/suins.ts, portal/server/app/route.ts, portal/worker/src/caching.ts, portal/worker/src/walrus-sites-sw.ts
This PR for Issue #211 adds a full-node fallback list to improve node reliability, enabling portal support for fallback nodes. It includes a fallback mechanism that creates a SuiClient instance for each RPC URL, ensuring resilience during network issues or rate limits.
**Changes:**
- RPC Selector: Introduced a singleton RPCSelector class that manages multiple SuiClient instances for efficient request handling across nodes.
- Fallback URLs: Added lists for testnetRPCUrls and prodRPCUrls to support testnet and mainnet failovers.
- API Refactor: Routed all SuiClient calls through RPCSelector to ensure reliable node selection during network issues or rate limiting.
Current RPC List:
1. fullnode.testnet.sui.io
2. sui-testnet.public.blastapi.io
3. sui-testnet-endpoint.blockvision.org
Not added …
=> feat(portal)!: Add full-node fallback list by instantiating a sui client for each rpc node

portal/worker/src/caching.ts, portal/worker/src/walrus-sites-sw.ts
1. Fixed the issue of the caching mechanism always "missing" in the service worker.
2. Updated the CACHE_EXPIRATION_TIME to 1 hour.
The resolveObjectId function would only be called on the site::Site object and not for each Resource (which makes sense as it is doing the suins-to-objectId resolution).
However, this meant that a lot of requests would be tagged as "cache miss" incorrectly, because the
site::Site version would be compared with the
site::Resource version inside the checkCachedVersionMatchesOnChain.
Thinking more about it, the end goal of using a cache is to avoid making requests to the RPC nodes.
Always checking for the sui object version contradicts this. Therefore I decided to remove the checkCachedVersionMatchesOnChain altogether.
Remember that caches expire, so at some …
=> fix(service-worker & cache): remove checkCachedVersionMatchesOnChain

portal/common/lib/decompress_data.ts, portal/common/lib/links.ts, portal/common/lib/logger.ts, portal/common/lib/objectId_operations.ts, portal/common/lib/page_fetching.ts, portal/common/lib/redirects.ts, portal/common/lib/resource.ts, portal/common/lib/routing.ts, portal/common/lib/rpc_selector.ts, portal/common/lib/suins.ts, portal/pnpm-lock.yaml, portal/server/app/route.ts, portal/server/instrumentation.ts, portal/server/next.config.mjs, portal/server/package.json, portal/server/sentry.client.config.ts, portal/server/sentry.edge.config.ts, portal/server/sentry.server.config.ts
**Changes**
- Integrate Sentry to the Logger implementation on the server portal.
- Update logs to send object looking like`{message: String, other-info: string}`.
For staging, I created a walrus-sites-sp-testnet project on Sentry which you can find [here](https://mysten-labs.sentry.io/traces/?environment=development&environment=vercel-preview&project=4508298139271168&statsPeriod=24h).
Note: the logs it contains are also from local development and there are a lot of trash from previous experiments. Need to clear it up later when I get access. 
**Future work**:
=> feat: integrate sentry to server portal

portal/common/lib/decompress_data.ts, portal/common/lib/links.ts, portal/common/lib/logger.ts, portal/common/lib/objectId_operations.ts, portal/common/lib/page_fetching.ts, portal/common/lib/redirects.ts, portal/common/lib/resource.ts, portal/common/lib/routing.ts, portal/common/lib/rpc_selector.ts, portal/common/lib/suins.ts, portal/pnpm-lock.yaml, portal/server/app/route.ts, portal/server/instrumentation.ts, portal/server/next.config.mjs, portal/server/package.json, portal/server/sentry.client.config.ts, portal/server/sentry.edge.config.ts, portal/server/sentry.server.config.ts
This class aims to be runtime-agnostic,
meaning that it should be able to run
in both the browser and on a server.
It is useful for cases where someone
needs to use a logging mechanism that
might be only supported on one runtime.
For example [amplitude](https://amplitude.com/docs/sdks/sdk-quickstart) provides different
interfaces (sdks) for different runtimes.
=> refactor: create logger class abstraction

move/walrus_site/Move.lock, move/walrus_site/sources/site.move, move/walrus_site/tests/site_tests.move, sites-config.yaml
- Add a burn function to the contract. 
- Fix: The `test_new_range_no_bounds_defined` should fail since at least one range bound should have been defined.
The `site-builder` will be updated when there will also be a `delete` argument support where both the blobs on walrus and the sui objects of a site will be deleted. 
_Warning: The burn function should be called after the `site-builder` has deleted all dynamic fields (resources and routes) attached to the site! Otherwise, deleting an object that has dynamic fields still defined on it [renders them all inaccessible](https://docs.sui.io/concepts/dynamic-fields#deleting-an-object-with-dynamic-fields) to future transactions!_
=> feat(contract): add a burn function to destroy unused old sites

site-builder/src/site/resource.rs, site-builder/src/walrus.rs, site-builder/src/walrus/output.rs
Updates the info-output format to align it with changes in https://github.com/MystenLabs/walrus/pull/1204.
=> fix: update info-output format and make request for n_shards more robust

.github/workflows/move-tests.yml, move/walrus_site/tests/site_tests.move
- new github action: downloads the sui binary, runs the tests and also checks if there is enough test coverage.
- new tests in the contract: increases test coverage in order to reach at least 80%.
=> feat(ops): add move-tests github action and improve test coverage

README.md
- start history: https://star-history.com/#MystenLabs/walrus-sites&Date.
- portal description: the README referred to only a single portal; the service worker. Now we have more, so I updated it.
- add a bullet point explaining what the `c4/` directory is used for.
- link directly to the walrus-sites docs instead of the walrus docs.
=> feat(docs): include a star-history graph and update the portal description

portal/server/app/route.ts, portal/server/custom_blocklist_checker.ts, portal/server/next.config.mjs, portal/server/sentry.client.config.ts, portal/server/sentry.edge.config.ts, portal/server/sentry.server.config.ts, portal/server/sentry_logger.ts, portal/worker/webpack.config.common.js
- Create `sentry_logger.ts`
- Create `custom_blocklist_checker.ts`
- Only integrate sentry and edge config upon production deployments, i.e. when running `pnpm run serve:prod:server`
=> refactor(portal): make sp locally deployable and vercel independent

move/walrus_site/sources/site.move, site-builder/src/main.rs, site-builder/src/publish.rs, site-builder/src/site.rs, site-builder/src/site/builder.rs, site-builder/src/site/contracts.rs, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs, site-builder/src/util.rs, sites-config.yaml
Closes SEINT-357
Closes SEINT-371
=> feat(site-builder): add new package to config, expose destroy command

site-builder/src/walrus/output.rs
I modified some response formats in Walrus a bit carelessly in https://github.com/MystenLabs/walrus/pull/1324 and included this in the 1.7.3 release. Unfortunately this broke the site-builder... 😬 
Would be nice to merge this into `main` and `testnet`.
=> fix: align response formats with Walrus

portal/common/lib/constants.ts, portal/common/lib/routing.ts
This change will save us from doing one additional request each time we need to fetch the `Routes` dynamic field. 
It derives the dynamic field object ID of `Routes` instead of fetching it.
=> feat(common-lib): derive routes df instead of fetch

portal/common/lib/routing.ts
There was an issue in the cases when a `Routes` dynamic field was not found, an exception would be thrown instead of showing a warning and returning `undefined` a.k.a. an implication that the df was _not found_.
=> fix(server-portal): return when Routes df is not found

Cargo.lock, site-builder/Cargo.toml, site-builder/src/backoff.rs, site-builder/src/main.rs, site-builder/src/publish.rs, site-builder/src/retry_client.rs, site-builder/src/site.rs, site-builder/src/site/contracts.rs, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs, site-builder/src/util.rs
Add multiple reliability improvements to shield the site builder from network errors and full node rate limiting. 
Specifically:
- All calls to the sui client are now wrapped and are retried with backoff
- OS network failures (os error 54) are retried when fetching the dynamic fields
In a follow up, would be nice to start using `multi_get_object`.
=> chore(site-builder): general reliability improvements

site-builder/src/main.rs, site-builder/src/publish.rs, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs
Introduces a new command, `update-resource`, with which a single resource can be added without verifying the state of the site object.
=> feat(site-builder): add single resource to existing site

portal/server/configuration_loader.ts, portal/server/sentry.client.config.ts, portal/server/sentry.edge.config.ts, portal/server/sentry.server.config.ts
Defining the `SENTRY_TRACES_SAMPLE_RATE`
can give us more flexibility to increase and
decrease this number based on the traffic we get
without the need of creating PRs and changing
the code directly.
=> feat: create SENTRY_TRACES_SAMPLE_RATE env variable

portal/common/lib/types/index.ts
In the `isRangeValid` function, the previous check for `range.start !== null && range.end !== null` was incorrect. It has been updated to properly check if both `start` and `end` are `null` using `range.start == null && range.end == null`.
This ensures that a valid range is correctly determined when both `start` and `end` are `null`, and fixes the validation logic to work as intended.
- Fixed the logic to validate range properly.
- Added additional checks to ensure valid range values.
- Improved range validation to handle `null` and negative values correctly.
=> fix: Correct range validation logic in isRangeValid function

portal/server/web_analytics.ts
Bonus: Custom event properties in the Pro plan
cannot exceed 2 in total. So I deleted the unused ones.
=> fix(portal): decrease number of events tracked per page-view

portal/server/web_analytics.ts
We would like to only track pageview events for html pages. 
Static files should be excluded. The previous PR included a very weak condition (url should end with `.html`).
This PR build on top of it, improving that condition by using the `getSubdomainAndPath` from the common library.
Also, I renamed the custom event to `pageview` - hopefully this will fix the vercel UI to automatically display this first without any filter.
=> fix(portal): improve vercel web analytics event sampling

portal/common/lib/objectId_operations.ts
The error from the logger would show up as
something crucial on Sentry, which is not.
Actually this is not even an error, because
the code will always "fail", e.g. return null
for suins domains
=> fix(common-lib): remove error from subdomainToObjectId

portal/common/lib/types/index.ts, portal/server/url_fetcher_factory.ts
Corrected the RPCSelector logic in UrlFetcherFactory to align with the intended functionality for premium and standard URL fetchers.
- `premiumUrlFetcher` now uses `premiumRpcSelector` to ensure it leverages premium RPC nodes for faster and more reliable content delivery.
- `standardUrlFetcher` now uses `standardRpcSelector` to appropriately use standard RPC nodes for basic operations.
- Previously, the `premiumUrlFetcher` and `standardUrlFetcher` were incorrectly assigned RPC selectors. This caused a mismatch in behavior where premium fetchers were using standard nodes and vice versa.
- This fix ensures the fetchers work as intended, maintaining performance expectations and fulfilling the logic outlined in the class's documentation.
This change resolves the logical inconsistency and …
=> Fix RPC Selector Logic in UrlFetcherFactory

portal/common/lib/routing.ts
We are currently getting errors for trying to reduce an empty array. 
Checking the filtered routes result will resolve this.
=> fix(common-lib): initialize array to avoid reducing empty array error

portal/common/lib/rpc_selector.ts, portal/common/lib/suins.test.ts, portal/common/lib/suins.ts, portal/common/lib/types/index.ts, portal/common/package.json, portal/pnpm-lock.yaml
This PR integrates the new functionality of SuiNS name records supporting a `walrusSiteId` to enable sites to connect with both a wallet and a walrus site. For backwards compatibility, we fall back to `nameRecord.targetAddress`.
Note: We don't need to use a `rpcSelector.validateSuinsResponse` because if the full node fails to return something valid, it throws an error that we catch on an outer try/catch block. 
- install `@mysten/suins`
- upgrade `@mysten/sui` to `1.18.1` to be compatible with suins.
- add `getNameRecord` call to `WrappedSuiClient`.
- create a new `NameRecord` type in `common/types` since the suins lib does not export it.
- update `SuiNSResolver` to use `rpcSelector.getNameRecord`.
- update unit tests accordingly.
=> feat(common): support for new SuiNS walrus site id resolution

portal/common/lib/resource.test.ts, portal/common/lib/routing.test.ts, portal/common/lib/rpc_selector.ts, portal/common/lib/suins.test.ts, portal/common/lib/types/index.ts, portal/server/configuration_loader.ts, portal/server/url_fetcher_factory.ts, portal/worker/src/walrus-sites-sw.ts, portal/worker/webpack.config.common.js
- Add `network` param to the RPC selector's constructor.
- Parse the `SUINS_CLIENT_NETWORK` field from the environment variables.
=> feat: add SUINS_CLIENT_NETWORK to config

portal/bun.lock, portal/server/package.json, portal/server/src/amplitude.ts
The server side Amplitude SDK is dumb: it doesn't automatically parse the http request headers to display information about each user like vercel web analytics does. 
From the docs:
If you send data server-side instead of using an SDK, Amplitude cannot track these user properties automatically. You must instead set these properties explicitly. [Source](https://amplitude.com/docs/get-started/user-property-definitions#:~:text=If%20you%20send%20data%20server%2Dside%20instead%20of%20using%20an%20SDK%2C%20Amplitude%20cannot%20track%20these%20user%20properties%20automatically.%20You%20must%20instead%20set%20these%20properties%20explicitly.%C2%A0).
=> feat: sew 38 explicitly parse request information for amplitude

portal/server/src/utils.ts
We calculate if a page is an html page by the content-type header, so it's irrelevant to throw an exception when the url path is not parseable.
=> fix: isHtmlPage should not throw exception when path is not parseable

portal/server/next-env.d.ts, portal/server/src/configuration_loader.ts
Update the configuration loader zod parsing checks so that when redis urls are provided for the blocklist and allowlist, each database number should be defined correctly. This acts as a Ulysses pact, to prevent us from switching accidentally the db numbers.
i.e. we use the same redis instance for both databases. However, for each database a number should be defined.
The blocklist database should be database `0` and the allowlist the database `1`. 
e.g. 
- `BLOCKLIST_REDIS_URL = redis[s]://[[same-username][:same-password]@][same-host][:same-port][/0]`
- `ALLOWLIST_REDIS_URL = redis[s]://[[same-username][:same-password]@][same-host][:same-port][/1]`
=> chore: check that each redis url db number is defined correctly

portal/common/lib/url_fetcher.ts
Added a retry mechanism for fetching resources from the aggregator.
Changes:
- Introduced fetchWithRetry method to retry failed fetch requests up to 3 times with a delay.
- Updated UrlFetcher to use fetchWithRetry instead of direct fetch calls.
=> feat: retry fetch aggregator on exception

portal/docker/server/Dockerfile, portal/package.json, portal/server/app/route.ts, portal/server/package.json, portal/server/src/amplitude.ts
amplitude is kind of broken after being moved behind a LB
1. `request.nextUrl` is not being reliable behind a LB, it's showing something like `http://localhost:3000/something` in the log, we cannot infer subdomain from `localhost`
2. `ua = new uaparser.UAParser(request.headers.get("user-agent") ?? undefined);` will always fail as the `UAParser` due to constructor overload. By always passing a string to the constructor, we can avoid the confusion.
3. `request.headers.get("x-forwarded-for")` are something like `ip1, ip2` behind GCP LB, we should always take the first ip in the chain, otherwise Amplitude will be confused and show completely incorrect geo country.
=> fix: amplitude user agent header

site-builder/src/walrus/output.rs
Recently, support for blob extensions was added to the `walrus` CLI, this PR makes the site-builder compatible with these new outputs. See [here](https://github.com/MystenLabs/walrus-docs/actions/runs/13430256831/job/37537274187) for an example of the incompatibility.
This should be cherry-picked to the `testnet` branch.
=> fix(site-builder): fix parsing of blob extensions

portal/common/.env.test, portal/common/lib/http/http_error_responses.ts, portal/common/lib/routing.test.ts, portal/common/lib/url_fetcher.ts
When a website has a custom 404.html (e.g., from Next.js build), we incorrectly fetch it without checking routes first. This breaks routing functionality for websites that include 404.html in their build output. Modified route resolution order and added test case to verify proper behavior.
Fixes #400
=> fix: prevent 404.html override when routes exist

portal/server/src/sentry_logger.ts
When Sentry was enabled the console logs would lose their structure.
This PR fixes this by showing logs as they would be in the case where sentry is not enabled.
i.e.
**Before**
```
| "range":"null"
│ "rpcClientSelected":"https://fullnode.testnet.sui.io"
│ "fetchedResourceResult":"{\"path\":\"/projects2.png\",\"headers\":{},\"blob_id\":\"Dbt-53bmZNbD0LhqZw_2i-19heJATVXICE9YGI
```
**After**
```
│ {"message":"Add the range headers of the resource","range":"null"}
│ {"message":"RPC selected","rpcClientSelected":"https://fullnode.testnet.sui.io"}
│ {"message":"Successfully fetched resource!","fetchedResourceResult":"{\"path\":\"/projects2.png\",\"headers\":{},\"blob_id\":\"Dbt-53bmZNbD0LhqZw_2i-19heJATVXICE9YGI
```
=> fix(logs): when sentry is enabled logs should still be human readable

portal/docker/server/Dockerfile
1. `over/bun:1` will automatically use latest 1.x.x release, which is 1.2.4 now, but it has some compatibility issues with the current version of `zod` we're using, so fixing it to 1.2.1 as indicated in bun.lock
2. make base image cleaner, those env vars are needed only during building phase, so no need to be in the base image.
3. copy `public/` folder over so that we can serve `walrus-site-sw.js` for some 404 issues
=> chore: fix dockerfile

site-builder/src/walrus/output.rs
This needs to be merged in both `main` and `testnet`.
=> fix: make encoding type compatible with latest Walrus version

portal/blocklist_api/src/index.ts
`/health` should be public, otherwise LB healthcheck will see `Unauthorized`
Tested with live deployment, working as expected, other paths are still under bearer token guard
=> fix: health check should be public

portal/blocklist_api/src/index.ts
we should check redis client liveness for health check
=> chore: add redis ping check to blockapi healthcheck endpoint

portal/common/lib/routing.test.ts, portal/common/lib/suins.ts, portal/common/lib/url_fetcher.ts, portal/docker/server/Dockerfile, portal/server/.env.example, portal/server/app/route.ts, portal/server/src/configuration_loader.ts, portal/server/src/url_fetcher_factory.ts, portal/worker/src/walrus-sites-sw.ts, site-builder/src/publish.rs
- Create a B36_DOMAIN_RESOLUTION_SUPPORT environment variable.
- Integrate it to the UrlFetcher class.
- The landing page b36 will always resolve to an object Id regardless of B36_DOMAIN_RESOLUTION_SUPPORT.
- Add B36_DOMAIN_RESOLUTION_SUPPORT to the server/Dockerfile.
- ⚠️ The service worker will always support b36 domains. 
- Update the site-builder publish output string. (`Browse the site with ...`).
Related PR on sui-operations: https://github.com/MystenLabs/sui-operations/pull/5078
=> feat(portal): sew 82 testnet portal until mainnet should not support b36 domains

README.md
- Our repo visitors most probably glance through our README first before clicking any link to the docs. It would be wiser to catch their attention with a very high level intro about sites.
- Reorder the file structure puting the user-facing components first.
- Use reference-style links instead of inlin links for a cleaner markdown.
=> docs: restructure and improve README

portal/common/lib/url_fetcher.ts
Minor fix related to the fetchWithRetry function.
=> fix: add missing lastError in fetch with retry

site-builder/src/types.rs
Fixes bug in the deserialization of the Routes VecMap
closes #370
=> fix: add custom deserialization to deserialize Move VecMap correctly

portal/common/lib/links.test.ts, portal/common/lib/links.ts, portal/common/vite.config.mts, portal/server/app/route.ts, portal/worker/src/walrus-sites-sw.ts
This was a security audit comment.
=> refactor(common): getObjectIdLink and getBlobId use URL input

move/walrus_site/Move.lock, move/walrus_site/sources/events.move, move/walrus_site/sources/metadata.move, move/walrus_site/sources/site.move, move/walrus_site/tests/site_tests.move, site-builder/src/site/builder.rs, sites-config.yaml
1. Include events for Site creation, deletion, etc. 
2. Refactor: create a separate Metadata module.
1. Rebuild the site-builder (note: this PR updates the packageId in the sites-config.yaml)
2. Publish the examples/snake.
3. Make a curl request to listen to one of the events introduced in the contract:
```
curl -X POST https://fullnode.testnet.sui.io:443 \
-H "Content-Type: application/json" \
-d '{
"jsonrpc": "2.0",
"id": 1,
"method": "suix_queryEvents",
"params": [
{
"MoveModule": {
"package": "0x9d055e60cc8012d43c396194395e8f80c54afd083d908bdfbc3c37906f59146e",
"module": "site",
"type": "0x9d055e60cc8012d43c396194395e8f80c54afd083d908bdfbc3c37906f59146e::events::SiteCreated"
}
},
null,
3,
false
]
}'
```
**Note**: The package id used above might have changed if there are more commits …
=> feat: sew 100 include events upon site creation and update

portal/docker/server/Dockerfile
Routes are available only for Bun v1.2.3+
=> fix(server-portal): bump Dockerfile Bun to 1.2.5

portal/bun.lock, portal/server/index.ts
Any request path that starts with `__wal__` will be a special path used by the portal for health checks etc.
=> chore: use a special __wal__ path

portal/bun.lock, portal/server/package.json, portal/server/src/cookie_monster.ts
Before, the cookie monster was eating only a single cookie, without setting the domain attribute
Now, it eats all the cookies.
Example:
```
reginaldosilva@MacBook-Pro portal % curl --verbose 'http://localhost:3000/'  -H'Cookie: barab=in; baraba=un' -H'Host: walrusadventures.walrus.site' >/dev/null 
* Host localhost:3000 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying [::1]:3000...
* Connected to localhost (::1) port 3000
> GET / HTTP/1.1
> Host: walrusadventures.walrus.site
> User-Agent: curl/8.7.1
> Accept: */*
> Cookie: barab=in; baraba=un
> 
* Request completely sent off
< HTTP/1.1 …
```
=> feat: improve Cookie Monster so it eats multiple cookies on all domains

portal/common/lib/http/http_error_responses.ts, portal/server/src/configuration_loader.ts, portal/server/src/main.ts
Tested with creating a .env file with `BRING_YOUR_OWN_DOMAIN=true/false` and without the variable all-together, and printing the output of Configuration, as well as visiting a subdomain.
=> feat(server-portal): do not allow subdomain access when BRING_YOUR_OWN_DOMAIN is true

site-builder/src/display.rs, site-builder/src/main.rs, sites-config.yaml
Adds a new configuration which has "contexts" (`mainnet` and `testnet`, in our config).
=> feat(site-builder): add multi-context config

site-builder/src/args.rs, site-builder/src/config.rs, site-builder/src/display.rs, site-builder/src/main.rs, site-builder/src/publish.rs, site-builder/src/site/content.rs, site-builder/src/site/manager.rs, site-builder/src/util.rs, site-builder/src/walrus.rs, site-builder/src/walrus/command.rs, sites-config.yaml
The context is now fully passed to the walrus binary, and the configuration also allows setting the `wallet_env`, such that it is not necessary anymore to select the environment using the `sui` CLI.
=> feat(site-builder): improve passing of context to walrus binary

site-builder/src/args.rs, site-builder/src/config.rs, site-builder/src/main.rs, site-builder/src/publish.rs, site-builder/src/site/manager.rs, site-builder/src/util.rs, sites-config.mainnet-singleton.yaml, sites-config.testnet-singleton.yaml, sites-config.yaml
- adds the option to specify a separate `walrus_context`
- adds the option to specify which `wallet_address` to use
- adds the option to specify a singleton config
=> feat(site-builder): add config for wallet address, walrus context, singleton config

examples/snake/ws-resources.json, site-builder/src/main.rs, site-builder/src/site/config.rs
- On WSResources change the site-name field(with a dash) to site_name
- On WSResources add the #[serde(deny_unknown_fields)] so that we throw an error. 
- On main.rs change the default site name from 'Test Site' to 'My Walrus Site'
- On config.rs add a test case for the invalid/valid site_name field.
=> fix(site-builder): Enforce site_name field and set a better default name

portal/common/html_templates/404-page-callback-if-missing.template.html, portal/common/lib/http/http_error_responses.ts, portal/common/lib/url_fetcher.ts
This pull request introduces a fallback mechanism for handling 404 errors by adding a default 404 page template and updating the logic to use it when a custom 404 page is unavailable. The changes include creating a new HTML template, modifying the response generation logic, and updating the URL fetcher to incorporate the fallback behavior.
* **New Default 404 Page Template**: Added `404-page-callback-if-missing.template.html` with a responsive design, light/dark mode support, and placeholders for dynamic messages.
* **Updated `Response404` Function**: Modified to accept an optional `template` parameter, defaulting to the primary 404 template but allowing the fallback template to be used.
* **New `custom404NotFound` Function**: Introduced a function that generates a 404 response using the …
=> feat(portal): add custom 404 fallback template and integrate into URL fetching logic

Cargo.lock, site-builder/Cargo.toml, site-builder/src/args.rs, site-builder/src/site/manager.rs, site-builder/src/walrus.rs, site-builder/src/walrus/command.rs
Release Notes:
- Backwards compatible interface change: Support defining epochs to store the site by using either `--epochs` or `--end-epoch` or `--earliest-expiry-time`.
=> feat(site-builder): Support --end-epoch or --earliest-expiry-time when for defining resources' end-epochs.

Cargo.lock, site-builder/Cargo.toml, site-builder/src/config.rs, site-builder/src/site/contracts.rs, site-builder/src/sitemap.rs, site-builder/src/types.rs, site-builder/src/util.rs, sites-config.yaml
This pull request introduces support for staking objects in the `site-builder` project, enabling enhanced functionality tied to staking parameters and expiration dates. The changes include updates to configuration files, new types and methods for handling staking objects, and modifications to existing logic to incorporate staking-related data.
* **Added `staking_object` field to `Config` struct**: Enables configuration of staking objects in `site-builder`. (`[site-builder/src/config.rsR35](diffhunk://#diff-2edbdfaec5661afb741e137ff2960e8c7b76bbbf8573d12a1f3d1c74a1d6f569R35)`)
* **Introduced `Staking` and `StakingInnerV1` types**: Represents staking objects and their inner state, including epoch duration, committees, and storage parameters. …
=> feat(site-builder): Displaying an expiration column on a site's resources when running sitemap

portal/server/package.json, portal/worker/package.json
The service worker and the server portal should each have a version associated with it.
We don't host a service worker, and we don't put much effort into it to be regarded as production ready, so I set it to 0.1.0.
The server portal on the other hand is production ready and battle tested, so I set it to 1.0.0.
=> chore(portal): sew 234 add versions to sw and sp portals

.github/workflows/move-tests.yml, move/walrus_site/Move.lock
Without fixing this it's not possible using the walrus sites smart contract as a dependency to another contract.
=> fix: SEW-295 update Move.lock to point at the latest testnet packageId

.github/workflows/server-portal-to-dockerhub.yml
This workflow actually triggers a gh action to another repository that actually does the work.
=> feat(ci/cd): add workflow to build and publish server-portal Docker image

.github/workflows/attach-binaries-to-release.yml
Adds the ubuntu-arm64 os to the list of oses to build artifacts for.
=> build(site-builder): Add ubuntu-arm64 to build list

portal/common/lib/quilt.test.ts, portal/common/lib/quilt.ts
Given a custom **resource header** like `"x-quilt-patch-internal-id": "0x0101000200"` (where `0x0101000200` in hex, the internal quilt patch identifier), and a **blob_id**, derive the **quilt patch id** in order to retrieve its contents from the aggregator endpoint.
e.g. 
```text
blob_id: jkZ5UWT2SPN46czhU-brz4JmQlc-bJlD14MiBzldouU
"x-quilt-patch-internal-id": "0x0101000200"
quilt patch id: jkZ5UWT2SPN46czhU-brz4JmQlc-bJlD14MiBzldouUBAQACAA
```
This PR is related to the Quilt integration with Walrus Sites.
=> feat(portal): derive `quiltpatchid` for resource retrieval

portal/bun.lock, portal/common/lib/aggregator.test.ts, portal/common/lib/aggregator.ts, portal/common/lib/quilt.test.ts, portal/common/lib/quilt.ts, portal/common/lib/redirects.test.ts, portal/common/lib/redirects.ts, portal/common/lib/url_fetcher.ts, portal/server/package.json, portal/worker/src/walrus-sites-sw.ts
When a site resource is stored as a quilt patch, a different URL should be used to fetch its' contents from the aggregator. 
Therefore, I created two kinds of URL constructors for each case:
1. for blob based resources: `blobAggregatorEndpoint`
2. for quilt based resources: `quiltAggregatorEndpoint`
Bonus:
- Fix the docker image by reintroducing the `@vercel/edge-config` dependency because it was removed by mistake
from `package.json` at commit https://github.com/MystenLabs/walrus-sites/commit/f069cbe59b31c74a0cba33a5a837d09150647770
=> feat(portal): Retrieve quilt based resources

site-builder/src/walrus.rs
Running `cargo run --features quilts-experimental -- --context=testnet publish-quilts examples/snake --epochs=1` resulted in an error. This was due to the removal of the temporary hack along with the walrus version bump to v.1.32.0. 
I am re-introducing the hack to the code to fix it.
=> fix(site-builder): rollback quilt json_input hack

portal/common/lib/src/types/index.ts, portal/common/lib/tests/crypto.test.ts, portal/common/lib/tests/types.test.ts
Fix the optionalRangeToHeaders( start: 0, end: 10 }) so that instead of returning bytes=-10 it should
return bytes=0-10.
This way it aligns with how range headers should be constructed. https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Headers/Range
Since I am already adding tests for the type/index.ts I included more tests to improve our coverage.
=> fix(common-lib): nullish coalescing for range header building

Cargo.lock, deny.toml, site-builder/Cargo.toml, site-builder/src/site/manager.rs, site-builder/src/site/resource.rs, site-builder/tests/quilts_dry_run_regression.rs
- fix: on `resource.rs/read_dir_and_store_quilts` an issue with the chunks being consumed with `unzip()` in the dry_run block which resulted in a bug.
- test: add the `quilts_dry_run_regression.rs` testing the snake site as well as a dummy large site, with the `publish-quilts —dry-run` command.
- Note1: added some `tracing:debug! `statements, not sure if we want to keep them
- Note2: I tried implementing a cleaner solution with a “ConfirmationProvider” Trait, that wraps the dialoguer, so that we could mock it with a programmatic one, so that we can test the dry-run without the “subprocess” hack. However, it felt like we have too much tight coupling in our codebase, which requires a huge refactor in order to enable this sort of dependency injection. So I went back to the “subprocess” hack …
=> fix(site-builder): using dry run throws error for publish quilts 

Cargo.lock, Cargo.toml, portal/bun.lock, portal/server/package.json, portal/worker/package.json, site-builder/Cargo.toml
Bump site-builder, server, and worker versions to 1.2.1
=> chore(release): bump site-builder, server, and worker versions to 1.2.1
